Neo4j nodes with count metadata option implemented
opendatadiscovery/odd-neo4j-adapter pull request #1
Opened 2021-11-08 12:11 UTC by dliubimov

2021-11-08 12:19 UTC, ruscooler approved these changes

2021-11-08 12:36 UTC, DementevNikita commented on odd_neo4j_adapter/mappers/__init__.py
> +_match_all_nodes: str = 'MATCH (n) RETURN distinct labels(n), count(*)'
Is it the query you gathering nodes with? If so, can we remove that from `mappers` package? It seems off to me to keep that here tbh

2021-11-08 12:42 UTC, DementevNikita commented on odd_neo4j_adapter/cache.py
> +        # data_entities_filtered = [
Can you remove the commented section?

2021-11-08 12:42 UTC, DementevNikita commented on odd_neo4j_adapter/adapter.py
> +    # replace
What for?

2021-11-08 12:42 UTC, DementevNikita requested changes
Comments

2021-11-09 13:56 UTC, DementevNikita approved these changes

2021-11-09 13:56 UTC, merged