neo4j fields added
opendatadiscovery/odd-neo4j-adapter pull request #4
Opened 2021-11-19 06:11 UTC by dliubimov

2021-11-19 07:53 UTC, DementevNikita requested changes

2021-11-19 07:53 UTC, DementevNikita commented on odd_neo4j_adapter/mappers/fields.py
> +            type=Type.TYPE_STRING,
I understand that this type is a sort of stub for now, but still let's define logical_type

2021-11-19 07:54 UTC, DementevNikita commented
also, why did the poetry.lock change? @ruscooler, is it ok?

2021-11-19 12:21 UTC, ruscooler commented
> also, why did the poetry.lock change? @ruscooler, is it ok?

yes, it's ok.

2021-11-22 15:27 UTC, DementevNikita approved these changes

2021-11-22 15:27 UTC, merged